name: deploy-book
on:
  push:
    branches: [main]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -U jupyter-book

      - run: jupyter-book build .

      - uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html

      - uses: actions/deploy-pages@v4
